apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
  namespace: default
  labels:
    app: search
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: search
  template:
    metadata:
      labels:
        pod: search
    spec:
      containers:
        - name: search
          image: "{{ .Values.image.repository}}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 9100
          resources: { }
          env:
            - name: ELASTIC_HOST
              value: elasticsearch.kube-logging
      imagePullSecrets:
        - name: gitlab-regcred
      restartPolicy: Always

status: {}