kind: Service
apiVersion: v1
metadata:
  name: search-service
  namespace: default
spec:
  type: NodePort
  selector:
    pod: search
  ports:
    - port: 9100
      targetPort: 9100
      nodePort: 30015